# -*- coding: utf-8 -*-
"""JUN107-FF.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MaAOikjy_Oyh8lrXEsFuHjZ65xZ07l3Y

1: Dimensionality Reduction on Customer Review Dataset

Task - 1
#Load TF-IDF feature matrix and sentiment labels
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA
from sklearn.manifold import TSNE
from sklearn.metrics.pairwise import euclidean_distances

random_seed = 10

df = pd.read_csv('custrev.csv')
tfidf_df = pd.read_csv('tfidf_features.csv')

y = df['label'].values
X = tfidf_df.values

print(f"Dataset shape: {X.shape}")
print(f"Label distribution:\n{df['label'].value_counts()}")

"""Curse of dimensionality
#calculate average pairwise Euclidean distance across diffrent dimensions
"""

dimensions_to_test = [10, 50, 100, 200, 500]
average_distances = []

for dim in dimensions_to_test:
    data_subset = X[:100, :dim]
    distances = euclidean_distances(data_subset)
    unique_distances = distances[np.triu_indices(100, k=1)]
    avg_dist = np.mean(unique_distances)
    average_distances.append(avg_dist)
    print(f"Dimensions: {dim}, Average Euclidean Distance: {avg_dist:.4f}")

plt.figure(figsize=(12, 6))
plt.grid()
plt.plot(dimensions_to_test, average_distances, marker='o')
plt.xlabel("Number of Dimensions")
plt.ylabel("Average Euclidean Distance")
plt.title("Curse of Dimensionality")
plt.show()

"""PCA

#Apply PCA to determine the number of components required to retain 90% variance

Calculate cumulative explained variance
"""

pca = PCA(random_state=random_seed)
pca.fit(X)

cumulative_variance = np.cumsum(pca.explained_variance_ratio_)
comps_num = np.arange(1, len(cumulative_variance) + 1)
n90 = np.where(cumulative_variance >= 0.90)[0][0] + 1

plt.figure(figsize=(12, 6))
plt.grid()
plt.plot(comps_num, cumulative_variance)
plt.axhline(y=0.90, color='r', linestyle='--', label='90% Variance')
plt.axvline(x=n90, color='g', linestyle='--', label=f'{n90} components')
plt.xlabel("Number of Components")
plt.ylabel("Cumulative Explained Variance")
plt.title("Cumulative Explained Variance by Number of Components")
plt.legend()
plt.show()

print(f"Components needed for 90% variance: {n90}")

print("\nTop 5 components:")
for i in range(5):
    print(f"  Component {i+1}: {pca.explained_variance_ratio_[i]:.4f}")
print(f"  Total: {pca.explained_variance_ratio_[:5].sum():.4f}")

"""# Generate 2D PCA visualisation"""

pca = PCA(n_components=2, random_state=random_seed)
X_pca = pca.fit_transform(X)
print(f"\nTotal explained variance (2 components): {sum(pca.explained_variance_ratio_):.4f}")

plt.figure(figsize=(12, 6))
plt.grid()
scatter = plt.scatter(X_pca[:, 0], X_pca[:, 1], c=y, s=20)
handles, _ = scatter.legend_elements()
plt.legend(handles, ['Negative', 'Positive'])
plt.xlabel("PC1")
plt.ylabel("PC2")
plt.title("PCA - 2 Components")
plt.show()

"""# Generate 3D PCA visualisation"""

pca = PCA(n_components=3, random_state=random_seed)
X_pca_3d = pca.fit_transform(X)
print(f"Total explained variance (3 components): {sum(pca.explained_variance_ratio_):.4f}")

fig = plt.figure(figsize=(10, 10))
ax = fig.add_subplot(projection='3d')
scatter = ax.scatter(X_pca_3d[:, 0], X_pca_3d[:, 1], X_pca_3d[:, 2], c=y, s=20)
ax.legend(handles, ['Negative', 'Positive'])
ax.set(xlabel='PC1', ylabel='PC2', zlabel='PC3')
plt.title("PCA - 3 Components")
plt.show()

"""# Apply t-SNE using PCA-reduced features"""

pca = PCA(n_components=n90, random_state=random_seed)
X_pca_reduced = pca.fit_transform(X)
print(f"\nPCA reduced shape: {X_pca_reduced.shape}")

# KL divergence for 1, 2, 3 components
tsne_comps_num = np.arange(1, 3+1)
tsne_comps_divergence = []

for num_components in tsne_comps_num:
    tsne = TSNE(n_components=num_components, random_state=random_seed)
    tsne.fit(X_pca_reduced)
    tsne_comps_divergence.append(tsne.kl_divergence_)
    print(f"KL Divergence for {num_components} component(s): {tsne.kl_divergence_:.4f}")

"""# Evaluate different perplexity values for optimal t-SNE performance"""

tsne_perplexity_num = np.arange(5, 50+1, 5)
tsne_perplexity_divergence = []

for perplexity in tsne_perplexity_num:
    tsne = TSNE(n_components=2, perplexity=perplexity, random_state=random_seed)
    tsne.fit(X_pca_reduced)
    tsne_perplexity_divergence.append(tsne.kl_divergence_)
    print(f"KL Divergence for perplexity {perplexity}: {tsne.kl_divergence_:.4f}")

plt.figure(figsize=(12, 6))
plt.grid()
plt.plot(tsne_perplexity_num, tsne_perplexity_divergence, marker='o')
plt.xlabel("Perplexity")
plt.ylabel("KL Divergence")
plt.title("t-SNE: KL Divergence vs Perplexity")
plt.show()

best_perplexity = tsne_perplexity_num[np.argmin(tsne_perplexity_divergence)]
print(f"\nBest perplexity: {best_perplexity}")

# 2 components
tsne = TSNE(n_components=2, perplexity=best_perplexity, random_state=random_seed)
X_tsne = tsne.fit_transform(X_pca_reduced)
print(f"KL Divergence (2 components, perplexity={best_perplexity}): {tsne.kl_divergence_:.4f}")

plt.figure(figsize=(12, 6))
plt.grid()
scatter = plt.scatter(X_tsne[:, 0], X_tsne[:, 1], c=y, s=20)
handles, _ = scatter.legend_elements()
plt.legend(handles, ['Negative', 'Positive'])
plt.xlabel("C1")
plt.ylabel("C2")
plt.title(f"t-SNE - 2 Components (perplexity={best_perplexity})")
plt.show()

# 3 components
tsne = TSNE(n_components=3, perplexity=best_perplexity, random_state=random_seed)
X_tsne_3d = tsne.fit_transform(X_pca_reduced)

fig = plt.figure(figsize=(10, 10))
ax = fig.add_subplot(projection='3d')
scatter = ax.scatter(X_tsne_3d[:, 0], X_tsne_3d[:, 1], X_tsne_3d[:, 2], c=y, s=20)
handles, _ = scatter.legend_elements()
ax.legend(handles, ['Negative', 'Positive'])
ax.set(xlabel='C1', ylabel='C2', zlabel='C3')
plt.title(f"t-SNE - 3 Components (perplexity={best_perplexity})")
plt.show()

"""Task 2
Data preprocessing

# Load churn dataset
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.metrics import silhouette_score

random_state = 10

# Load data
df = pd.read_csv('churn.csv')
df.info()

df

df.describe()

print("Missing values:\n", df.isnull().sum())
print("\nExited distribution:\n", df['Exited'].value_counts())
print("\nGeography distribution:\n", df['Geography'].value_counts())

"""# Remove CustomerId as it has no predictive value"""

df = df.drop(columns=['CustomerId'])

# Encode Exited
le = LabelEncoder()
df['Exited'] = le.fit_transform(df['Exited'])  # No=0, Yes=1

# Model 1: Clustering without Geography
features = ['CreditScore', 'Age', 'Balance', 'EstimatedSalary']

X = df[features].to_numpy()

scaler = StandardScaler()
X = scaler.fit_transform(X)

"""# Elbow method"""

clusters = []
inertia_vals = []

for k in range(2, 9):
    model = KMeans(n_clusters=k, random_state=random_state)
    model.fit(X)
    clusters.append(model)
    inertia_vals.append(model.inertia_)

plt.figure(figsize=(12, 6))
plt.grid()
plt.plot(range(2, 9), inertia_vals, marker='o')
plt.xlabel("Number of Clusters (K)")
plt.ylabel("Inertia")
plt.title("Elbow Method")
plt.show()

"""# Silhouette scores"""

for i, k in enumerate(range(2, 9)):
    score = silhouette_score(X, clusters[i].predict(X))
    print(f"Silhouette score for k={k}: {score:.4f}")

# Fit K=4
model = KMeans(n_clusters=4, random_state=random_state)
model.fit(X)

print("Sum of intra-cluster distance:", model.inertia_)
print("Centroid locations:")
for centroid in model.cluster_centers_:
    print(centroid)

"""# Assign cluster labels"""

y = model.predict(X)
df['Cluster_ID'] = y

print("\nCluster membership:")
print(df['Cluster_ID'].value_counts())

print("\nExited rate per cluster:")
print(df.groupby('Cluster_ID')['Exited'].mean().round(3))

"""# Centroids in original scale"""

centroids = pd.DataFrame(scaler.inverse_transform(model.cluster_centers_), columns=features)
centroids.index.name = 'Cluster'
print("\nCluster centroids (original scale):")
print(centroids.round(2))

"""# Pairplot"""

df2 = df[features + ['Cluster_ID']].copy()
cluster_g = sns.pairplot(df2, hue='Cluster_ID', diag_kind='hist')
plt.show()

"""# Cluster distribution plots"""

fig, axes = plt.subplots(2, 2, figsize=(12, 8))
for ax, var in zip(axes.flatten(), features):
    for c in range(4):
        ax.hist(df[df['Cluster_ID'] == c][var], bins=30, alpha=0.5, label=f'Cluster {c}')
    ax.set_title(f'Distribution of {var}')
    ax.set_xlabel(var)
    ax.set_ylabel('Count')
    ax.legend()
    ax.grid()
plt.suptitle('Feature Distributions per Cluster (Model 1)', fontsize=13)
plt.tight_layout()
plt.show()

# Model 2: Clustering with Geography
df2 = df.copy()

"""# Encode Geography with LabelEncoder"""

le_geo = LabelEncoder()
df2['Geography'] = le_geo.fit_transform(df2['Geography'])

features2 = ['CreditScore', 'Age', 'Balance', 'EstimatedSalary', 'Geography']

X2 = df2[features2].to_numpy()

scaler2 = StandardScaler()
X2 = scaler2.fit_transform(X2)

model2 = KMeans(n_clusters=4, random_state=random_state)
model2.fit(X2)

y2 = model2.predict(X2)
df2['Cluster_ID'] = y2

print("Model 2 cluster membership:")
print(df2['Cluster_ID'].value_counts())

print(f"\nModel 1 silhouette score: {silhouette_score(X, model.predict(X)):.4f}")
print(f"Model 2 silhouette score: {silhouette_score(X2, model2.predict(X2)):.4f}")

print("\nExited rate per cluster (Model 2):")
print(df2.groupby('Cluster_ID')['Exited'].mean().round(3))

"""# Pairplot Model 2"""

cluster_g2 = sns.pairplot(df2[features2 + ['Cluster_ID']], hue='Cluster_ID', diag_kind='hist')
plt.show()



"""# 3: Time Series Prediction using LSTM on the AgriWebb Dataset

## 3.1 Import Libraries
"""

# Import deep learning libraries
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_squared_error, mean_absolute_error

import math

print("Deep learning libraries imported successfully!")

"""## 3.2 Load and Explore Dataset

The `soil_data.csv` dataset has already been loaded and explored in the previous sections. We will continue using `df_soil_processed`, `df_train`, and `df_test` which were created during preprocessing.

## 3.3 Data Preprocessing

Data preprocessing steps (converting `OBSERVATION_DATE`, sorting, and splitting into train/test sets based on `PADDOCK_ID` and reserving the last 6 timesteps) have already been performed in the earlier `df_soil` analysis. We will use the `df_train` and `df_test` DataFrames created previously.

## 3.4 Feature Scaling
"""

import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler

# Define PREDICT_TIMESTEPS (used in train/test split logic)
PREDICT_TIMESTEPS = 6

# Load the dataset (assuming soil_data.csv is available in the environment)
df_soil = pd.read_csv('soil_data.csv')

# Convert 'OBSERVATION_DATE' to datetime and sort
df_soil['OBSERVATION_DATE'] = pd.to_datetime(df_soil['OBSERVATION_DATE'])
df_soil = df_soil.sort_values(by=['PADDOCK_ID', 'OBSERVATION_DATE']).reset_index(drop=True)

# Split into training and testing sets
# For each PADDOCK_ID, the last PREDICT_TIMESTEPS rows go to df_test, the rest to df_train
df_train = df_soil.groupby('PADDOCK_ID').apply(lambda x: x.iloc[:-PREDICT_TIMESTEPS]).reset_index(drop=True)
df_test = df_soil.groupby('PADDOCK_ID').apply(lambda x: x.iloc[-PREDICT_TIMESTEPS:]).reset_index(drop=True)

# LSTM models often perform better with scaled data, typically within a range like 0-1.
# MinMaxScaler is a good choice for this purpose.

# Identify numerical features for scaling. Exclude PADDOCK_ID and OBSERVATION_DATE.
numerical_features = df_train.select_dtypes(include=np.number).columns.tolist()
# Remove PADDOCK_ID if it was included as a number for scaling, as it's an identifier.
if 'PADDOCK_ID' in numerical_features:
    numerical_features.remove('PADDOCK_ID')

# Initialize MinMaxScaler
scaler = MinMaxScaler(feature_range=(0, 1))

# Apply scaler to the training data
# Fit on training data only to prevent data leakage from the test set.
scaled_train_data = scaler.fit_transform(df_train[numerical_features])

# Transform the test data using the scaler fitted on the training data
scaled_test_data = scaler.transform(df_test[numerical_features])

# Convert scaled arrays back to DataFrames for easier handling
df_scaled_train = pd.DataFrame(scaled_train_data, columns=numerical_features)
df_scaled_test = pd.DataFrame(scaled_test_data, columns=numerical_features)

print("Numerical features in training and testing datasets scaled using MinMaxScaler.")
print("First 5 rows of scaled training data:")
display(df_scaled_train.head())
print("\nFirst 5 rows of scaled testing data:")
display(df_scaled_test.head())

print("Note: LSTM models perform better with scaled data, often normalized to a range like 0-1.")

"""## 3.5 Create Sequences for Model 1

> Add blockquote


"""

# Function to create sequences for LSTM training
# X: sequences of 'lookback' timesteps from the input data
# y: sequences of 'predict_timesteps' target values immediately following the lookback window
def create_train_sequences(data_scaled_df, original_paddock_ids_series, lookback, predict_timesteps, target_feature, numerical_features_list):
    X, y = [], []
    unique_paddocks = original_paddock_ids_series.unique()
    target_feature_index = numerical_features_list.index(target_feature)

    for paddock_id in unique_paddocks:
        # Get data for the current paddock
        paddock_data_scaled = data_scaled_df[original_paddock_ids_series == paddock_id].values

        # Loop through the paddock data to create sequences
        # We need enough data for the lookback window and the prediction window
        for i in range(len(paddock_data_scaled) - lookback - predict_timesteps + 1):
            X.append(paddock_data_scaled[i:(i + lookback)])
            y.append(paddock_data_scaled[(i + lookback):(i + lookback + predict_timesteps), target_feature_index])

    return np.array(X), np.array(y)

# Function to create sequences for LSTM evaluation (predicting the reserved test set)
# X_eval: last 'lookback' timesteps from training data for each paddock
# y_eval: 'predict_timesteps' target values from test data for each paddock
def create_eval_sequences(df_scaled_train, df_train_paddock_ids, df_scaled_test, df_test_paddock_ids, lookback, predict_timesteps, target_feature, numerical_features_list):
    X_eval, y_eval = [], []
    unique_paddocks_in_test = df_test_paddock_ids.unique()
    target_feature_index = numerical_features_list.index(target_feature)

    for paddock_id in unique_paddocks_in_test:
        train_paddock_data_scaled = df_scaled_train[df_train_paddock_ids == paddock_id]
        test_paddock_data_scaled = df_scaled_test[df_test_paddock_ids == paddock_id]

        if len(train_paddock_data_scaled) < lookback:
            print(f"Skipping paddock {paddock_id} for evaluation: not enough training data ({len(train_paddock_data_scaled)} timesteps) for lookback window ({lookback}).")
            continue
        if len(test_paddock_data_scaled) != predict_timesteps:
            print(f"Skipping paddock {paddock_id} for evaluation: test data has {len(test_paddock_data_scaled)} timesteps, expected {predict_timesteps}.")
            continue

        # Input sequence for prediction: the last 'lookback' timesteps from the training set
        X_eval.append(train_paddock_data_scaled.iloc[-lookback:].values)

        # Target sequence for evaluation: the actual 'predict_timesteps' from the test set
        y_eval.append(test_paddock_data_scaled.iloc[:, target_feature_index].values)

    return np.array(X_eval), np.array(y_eval)


# Define lookback and prediction steps
LOOKBACK_M1 = 5
PREDICT_TIMESTEPS = 6
TARGET_FEATURE = 'SOIL_MOISTURE'

print(f"Creating training sequences with lookback = {LOOKBACK_M1} and predicting next {PREDICT_TIMESTEPS} timesteps for '{TARGET_FEATURE}'.")

# Create sequences for training data
X_train_m1, y_train_m1 = create_train_sequences(df_scaled_train, df_train['PADDOCK_ID'], LOOKBACK_M1, PREDICT_TIMESTEPS, TARGET_FEATURE, numerical_features)

print(f"Shape of X_train_m1: {X_train_m1.shape}") # (samples, lookback, features)
print(f"Shape of y_train_m1: {y_train_m1.shape}") # (samples, predict_timesteps)

print(f"\nCreating evaluation sequences for Model 1 (X from end of train, y from test) with lookback = {LOOKBACK_M1}.")
# Create sequences for testing data (for evaluation)
X_test_m1, y_test_m1 = create_eval_sequences(df_scaled_train, df_train['PADDOCK_ID'], df_scaled_test, df_test['PADDOCK_ID'], LOOKBACK_M1, PREDICT_TIMESTEPS, TARGET_FEATURE, numerical_features)

print(f"Shape of X_test_m1: {X_test_m1.shape}")
print(f"Shape of y_test_m1: {y_test_m1.shape}")

print("\nFirst sample of X_train_m1 (input sequence):")
print(X_train_m1[0])
print("\nFirst sample of y_train_m1 (target sequence for SOIL_MOISTURE):")
print(y_train_m1[0])

if len(X_test_m1) > 0:
    print("\nFirst sample of X_test_m1 (input sequence for evaluation):")
    print(X_test_m1[0])
    print("\nFirst sample of y_test_m1 (actual target sequence for evaluation):")
    print(y_test_m1[0])

"""## 3.6 Build Univariate LSTM Model 1"""

# Define the LSTM model architecture
model1 = Sequential([
    # LSTM layer with 64 units, returning sequences for the next layer if stacked, or not if it's the last.
    # input_shape expects (timesteps, features). For univariate, features=1. For multivariate, features > 1.
    # Here, we are predicting one feature (SOIL_MOISTURE) so we need to ensure the input is correct.
    # X_train_m1.shape is (samples, lookback, features).
    LSTM(64, activation='relu', input_shape=(LOOKBACK_M1, X_train_m1.shape[2])),
    # Dense layer for output. Since we are predicting 6 future timesteps, the output layer has 6 units.
    Dense(PREDICT_TIMESTEPS)
])

# Compile the model
model1.compile(optimizer='adam', loss='mse')

print("Univariate LSTM Model 1 built and compiled successfully!")
model1.summary()

# Train the model
# Use a validation split to monitor performance on unseen data during training
history1 = model1.fit(
    X_train_m1, y_train_m1,
    epochs=50, # Number of training iterations
    batch_size=32, # Number of samples per gradient update
    validation_split=0.2, # Use 20% of training data for validation
    verbose=1 # Display training progress
)

print("\nUnivariate LSTM Model 1 training complete.")

# Display training loss curve
plt.figure(figsize=(10, 6))
plt.plot(history1.history['loss'], label='Training Loss')
plt.plot(history1.history['val_loss'], label='Validation Loss')
plt.title('Univariate LSTM Model 1 Training Loss Curve')
plt.xlabel('Epoch')
plt.ylabel('Loss (MSE)')
plt.legend()
plt.grid(True)
plt.show()

# Evaluate Model 1

# Make predictions on the test data
# Ensure X_test_m1 is not empty before attempting prediction
y_pred_m1 = model1.predict(X_test_m1) if X_test_m1.shape[0] > 0 else np.array([])

# Only proceed with evaluation if predictions were made
if y_pred_m1.shape[0] > 0:
    # Invert scaling for actual and predicted values to get them in original units
    # We need to inverse transform only the 'SOIL_MOISTURE' column.
    # To do this, we create dummy arrays with zeros for other features and place the actual/predicted values into the correct column index.

    # The scaler was fitted on the entire numerical_features list.
    # We need to recreate the original structure for inverse_transform.
    # Find the index of the target feature (SOIL_MOISTURE) in the numerical_features list.
    target_feature_idx = numerical_features.index(TARGET_FEATURE)

    # Inverse transform y_test_m1
    y_test_m1_rescaled = np.zeros((y_test_m1.shape[0], y_test_m1.shape[1], len(numerical_features)))
    y_test_m1_rescaled[:, :, target_feature_idx] = y_test_m1
    # Reshape y_test_m1_rescaled to 2D for inverse_transform
    y_test_m1_rescaled_2d = y_test_m1_rescaled.reshape(-1, len(numerical_features))
    y_actual_original = scaler.inverse_transform(y_test_m1_rescaled_2d)[:, target_feature_idx]
    y_actual_original = y_actual_original.reshape(y_test_m1.shape)

    # Inverse transform y_pred_m1
    y_pred_m1_rescaled = np.zeros((y_pred_m1.shape[0], y_pred_m1.shape[1], len(numerical_features)))
    y_pred_m1_rescaled[:, :, target_feature_idx] = y_pred_m1
    # Reshape y_pred_m1_rescaled to 2D for inverse_transform
    y_pred_m1_rescaled_2d = y_pred_m1_rescaled.reshape(-1, len(numerical_features))
    y_pred_original = scaler.inverse_transform(y_pred_m1_rescaled_2d)[:, target_feature_idx]
    y_pred_original = y_pred_original.reshape(y_pred_m1.shape)

    # Calculate RMSE and MAE for each predicted timestep and then average them
    rmse_per_timestep = [np.sqrt(mean_squared_error(y_actual_original[:, i], y_pred_original[:, i])) for i in range(PREDICT_TIMESTEPS)]
    mae_per_timestep = [mean_absolute_error(y_actual_original[:, i], y_pred_original[:, i]) for i in range(PREDICT_TIMESTEPS)]

    global overall_rmse_m1, overall_mae_m1 # Declare global to make variables accessible later
    overall_rmse_m1 = np.mean(rmse_per_timestep)
    overall_mae_m1 = np.mean(mae_per_timestep)

    print(f"\nUnivariate LSTM Model 1 Evaluation (Lookback={LOOKBACK_M1}, Predict={PREDICT_TIMESTEPS}):")
    print(f"Overall RMSE: {overall_rmse_m1:.4f}")
    print(f"Overall MAE: {overall_mae_m1:.4f}")

    # Plot actual vs predicted values for a sample paddock or a few samples

    # Select a paddock for visualization (e.g., the first one in the test set)
    # This requires mapping back to original paddock IDs, which is a bit tricky with sequence creation.
    # For simplicity, let's just plot the first few prediction sequences.

    num_plots = min(3, y_actual_original.shape[0]) # Number of prediction sequences to plot, limit to available samples
    plt.figure(figsize=(15, 5 * num_plots))

    for i in range(num_plots):
        plt.subplot(num_plots, 1, i + 1)
        plt.plot(range(PREDICT_TIMESTEPS), y_actual_original[i], label='Actual SOIL_MOISTURE', marker='o')
        plt.plot(range(PREDICT_TIMESTEPS), y_pred_original[i], label='Predicted SOIL_MOISTURE', marker='x', linestyle='--')
        plt.title(f'Model 1: Actual vs. Predicted Soil Moisture (Test Sample {i+1})')
        plt.xlabel('Timestep (relative to prediction start)')
        plt.ylabel('Soil Moisture (Original Scale)')
        plt.legend()
        plt.grid(True)

    plt.tight_layout()
    plt.show()
else:
    print(f"Skipping evaluation for Model 1 as X_test_m1 was empty. Shapes: X_test_m1={X_test_m1.shape}, y_test_m1={y_test_m1.shape}")
    overall_rmse_m1 = float('nan') # Assign NaN if no evaluation
    overall_mae_m1 = float('nan')

"""

```
# This is formatted as code
```

## 3.7. Build Univariate LSTM Model 2"""

# Define lookback for Model 2
LOOKBACK_M2 = 10
PREDICT_TIMESTEPS = 6 # Remains the same as Model 1
TARGET_FEATURE = 'SOIL_MOISTURE'

print(f"Creating training sequences for Model 2 with lookback = {LOOKBACK_M2} and predicting next {PREDICT_TIMESTEPS} timesteps for '{TARGET_FEATURE}'.")

# Create sequences for training data with new lookback
X_train_m2, y_train_m2 = create_train_sequences(df_scaled_train, df_train['PADDOCK_ID'], LOOKBACK_M2, PREDICT_TIMESTEPS, TARGET_FEATURE, numerical_features)

print(f"Shape of X_train_m2: {X_train_m2.shape}") # (samples, lookback, features)
print(f"Shape of y_train_m2: {y_train_m2.shape}") # (samples, predict_timesteps)

print(f"\nCreating evaluation sequences for Model 2 (X from end of train, y from test) with lookback = {LOOKBACK_M2}.")
# Create sequences for testing data (for evaluation)
X_test_m2, y_test_m2 = create_eval_sequences(df_scaled_train, df_train['PADDOCK_ID'], df_scaled_test, df_test['PADDOCK_ID'], LOOKBACK_M2, PREDICT_TIMESTEPS, TARGET_FEATURE, numerical_features)

print(f"Shape of X_test_m2: {X_test_m2.shape}")
print(f"Shape of y_test_m2: {y_test_m2.shape}")

print("\nFirst sample of X_train_m2 (input sequence):")
print(X_train_m2[0])
print("\nFirst sample of y_train_m2 (target sequence for SOIL_MOISTURE):")
print(y_train_m2[0])

if len(X_test_m2) > 0:
    print("\nFirst sample of X_test_m2 (input sequence for evaluation):\n", X_test_m2[0])
    print("\nFirst sample of y_test_m2 (actual target sequence for evaluation):\n", y_test_m2[0])

# Define the LSTM model architecture for Model 2
model2 = Sequential([
    LSTM(64, activation='relu', input_shape=(LOOKBACK_M2, X_train_m2.shape[2])),
    Dense(PREDICT_TIMESTEPS)
])

# Compile the model
model2.compile(optimizer='adam', loss='mse')

print("Univariate LSTM Model 2 built and compiled successfully!")
model2.summary()

# Train the model
history2 = model2.fit(
    X_train_m2, y_train_m2,
    epochs=50,
    batch_size=32,
    validation_split=0.2,
    verbose=1
)

print("\nUnivariate LSTM Model 2 training complete.")

# Display training loss curve
plt.figure(figsize=(10, 6))
plt.plot(history2.history['loss'], label='Training Loss')
plt.plot(history2.history['val_loss'], label='Validation Loss')
plt.title('Univariate LSTM Model 2 Training Loss Curve')
plt.xlabel('Epoch')
plt.ylabel('Loss (MSE)')
plt.legend()
plt.grid(True)
plt.show()

# Evaluate Model 2

# Make predictions on the test data
y_pred_m2 = model2.predict(X_test_m2) if X_test_m2.shape[0] > 0 else np.array([])

# Only proceed with evaluation if predictions were made
if y_pred_m2.shape[0] > 0:
    # Inverse transform actual and predicted values to original scale
    y_test_m2_rescaled = np.zeros((y_test_m2.shape[0], y_test_m2.shape[1], len(numerical_features)))
    y_test_m2_rescaled[:, :, target_feature_idx] = y_test_m2
    y_actual_original_m2 = scaler.inverse_transform(y_test_m2_rescaled.reshape(-1, len(numerical_features)))[:, target_feature_idx]
    y_actual_original_m2 = y_actual_original_m2.reshape(y_test_m2.shape)

    y_pred_m2_rescaled = np.zeros((y_pred_m2.shape[0], y_pred_m2.shape[1], len(numerical_features)))
    y_pred_m2_rescaled[:, :, target_feature_idx] = y_pred_m2
    y_pred_original_m2 = scaler.inverse_transform(y_pred_m2_rescaled.reshape(-1, len(numerical_features)))[:, target_feature_idx]
    y_pred_original_m2 = y_pred_original_m2.reshape(y_pred_m2.shape)

    # Calculate RMSE and MAE
    rmse_per_timestep_m2 = [np.sqrt(mean_squared_error(y_actual_original_m2[:, i], y_pred_original_m2[:, i])) for i in range(PREDICT_TIMESTEPS)]
    mae_per_timestep_m2 = [mean_absolute_error(y_actual_original_m2[:, i], y_pred_original_m2[:, i]) for i in range(PREDICT_TIMESTEPS)]

    global overall_rmse_m2, overall_mae_m2 # Declare global
    overall_rmse_m2 = np.mean(rmse_per_timestep_m2)
    overall_mae_m2 = np.mean(mae_per_timestep_m2)

    print(f"\nUnivariate LSTM Model 2 Evaluation (Lookback={LOOKBACK_M2}, Predict={PREDICT_TIMESTEPS}):")
    print(f"Overall RMSE: {overall_rmse_m2:.4f}")
    print(f"Overall MAE: {overall_mae_m2:.4f}")

    # Compare performance
    print("\nComparison with Model 1:")
    print(f"Model 1 RMSE: {overall_rmse_m1:.4f}, MAE: {overall_mae_m1:.4f}")
    print(f"Model 2 RMSE: {overall_rmse_m2:.4f}, MAE: {overall_mae_m2:.4f}")
    if overall_rmse_m2 < overall_rmse_m1:
        print("Model 2 (larger lookback) shows improved RMSE compared to Model 1.")
    else:
        print("Model 2 (larger lookback) does not show improved RMSE compared to Model 1.")

    # Plot actual vs predicted values for a sample paddock or a few samples
    num_plots = min(3, y_actual_original_m2.shape[0]) # Number of prediction sequences to plot, limit to available samples
    plt.figure(figsize=(15, 5 * num_plots))

    for i in range(num_plots):
        plt.subplot(num_plots, 1, i + 1)
        plt.plot(range(PREDICT_TIMESTEPS), y_actual_original_m2[i], label='Actual SOIL_MOISTURE', marker='o')
        plt.plot(range(PREDICT_TIMESTEPS), y_pred_original_m2[i], label='Predicted SOIL_MOISTURE', marker='x', linestyle='--')
        plt.title(f'Model 2: Actual vs. Predicted Soil Moisture (Test Sample {i+1})')
        plt.xlabel('Timestep (relative to prediction start)')
        plt.ylabel('Soil Moisture (Original Scale)')
        plt.legend()
        plt.grid(True)

    plt.tight_layout()
    plt.show()
else:
    print(f"Skipping evaluation for Model 2 as X_test_m2 was empty. Shapes: X_test_m2={X_test_m2.shape}, y_test_m2={y_test_m2.shape}")
    overall_rmse_m2 = float('nan')
    overall_mae_m2 = float('nan')

"""## 3.8 Build Multivariate LSTM Model"""

# For the multivariate model, we will use all numerical features as inputs.
# The target feature remains 'SOIL_MOISTURE'.

# The scaled dataframes (df_scaled_train, df_scaled_test) already contain all numerical features.

# Define lookback and prediction steps for the multivariate model
LOOKBACK_M3 = 5 # Can be adjusted, using 5 for consistency with M1 initially
PREDICT_TIMESTEPS = 6
TARGET_FEATURE = 'SOIL_MOISTURE'

print(f"Creating training sequences for Multivariate Model with lookback = {LOOKBACK_M3} and predicting next {PREDICT_TIMESTEPS} timesteps for '{TARGET_FEATURE}'.")

# Create sequences for training data (X will now have multiple features per timestep)
X_train_m3, y_train_m3 = create_train_sequences(df_scaled_train, df_train['PADDOCK_ID'], LOOKBACK_M3, PREDICT_TIMESTEPS, TARGET_FEATURE, numerical_features)

print(f"Shape of X_train_m3: {X_train_m3.shape}") # (samples, lookback, features)
print(f"Shape of y_train_m3: {y_train_m3.shape}") # (samples, predict_timesteps)

print(f"\nCreating evaluation sequences for Model 3 (X from end of train, y from test) with lookback = {LOOKBACK_M3}.")
# Create sequences for testing data (for evaluation)
X_test_m3, y_test_m3 = create_eval_sequences(df_scaled_train, df_train['PADDOCK_ID'], df_scaled_test, df_test['PADDOCK_ID'], LOOKBACK_M3, PREDICT_TIMESTEPS, TARGET_FEATURE, numerical_features)

print(f"Shape of X_test_m3: {X_test_m3.shape}")
print(f"Shape of y_test_m3: {y_test_m3.shape}")

print("\nFirst sample of X_train_m3 (input sequence - multiple features):")
print(X_train_m3[0])
print("\nFirst sample of y_train_m3 (target sequence for SOIL_MOISTURE):")
print(y_train_m3[0])

if len(X_test_m3) > 0:
    print("\nFirst sample of X_test_m3 (input sequence for evaluation):\n", X_test_m3[0])
    print("\nFirst sample of y_test_m3 (actual target sequence for evaluation):\n", y_test_m3[0])

# Define the Multivariate LSTM model architecture
# The input_shape for LSTM will now reflect the number of features used (all numerical_features)
model3 = Sequential([
    LSTM(64, activation='relu', input_shape=(LOOKBACK_M3, X_train_m3.shape[2])),
    Dense(PREDICT_TIMESTEPS)
])

# Compile the model
model3.compile(optimizer='adam', loss='mse')

print("Multivariate LSTM Model built and compiled successfully!")
model3.summary()

# Train the model
history3 = model3.fit(
    X_train_m3, y_train_m3,
    epochs=50,
    batch_size=32,
    validation_split=0.2,
    verbose=1
)

print("\nMultivariate LSTM Model training complete.")

# Display training loss curve
plt.figure(figsize=(10, 6))
plt.plot(history3.history['loss'], label='Training Loss')
plt.plot(history3.history['val_loss'], label='Validation Loss')
plt.title('Multivariate LSTM Model Training Loss Curve')
plt.xlabel('Epoch')
plt.ylabel('Loss (MSE)')
plt.legend()
plt.grid(True)
plt.show()

# Evaluate Multivariate Model

# Make predictions on the test data
y_pred_m3 = model3.predict(X_test_m3) if X_test_m3.shape[0] > 0 else np.array([])

# Only proceed with evaluation if predictions were made
if y_pred_m3.shape[0] > 0:
    # Inverse transform actual and predicted values to original scale
    y_test_m3_rescaled = np.zeros((y_test_m3.shape[0], y_test_m3.shape[1], len(numerical_features)))
    y_test_m3_rescaled[:, :, target_feature_idx] = y_test_m3
    y_actual_original_m3 = scaler.inverse_transform(y_test_m3_rescaled.reshape(-1, len(numerical_features)))[:, target_feature_idx]
    y_actual_original_m3 = y_actual_original_m3.reshape(y_test_m3.shape)

    y_pred_m3_rescaled = np.zeros((y_pred_m3.shape[0], y_pred_m3.shape[1], len(numerical_features)))
    y_pred_m3_rescaled[:, :, target_feature_idx] = y_pred_m3
    y_pred_original_m3 = scaler.inverse_transform(y_pred_m3_rescaled.reshape(-1, len(numerical_features)))[:, target_feature_idx]
    y_pred_original_m3 = y_pred_original_m3.reshape(y_pred_m3.shape)

    # Calculate RMSE and MAE
    rmse_per_timestep_m3 = [np.sqrt(mean_squared_error(y_actual_original_m3[:, i], y_pred_original_m3[:, i])) for i in range(PREDICT_TIMESTEPS)]
    mae_per_timestep_m3 = [mean_absolute_error(y_actual_original_m3[:, i], y_pred_original_m3[:, i]) for i in range(PREDICT_TIMESTEPS)]

    global overall_rmse_m3, overall_mae_m3 # Declare global
    overall_rmse_m3 = np.mean(rmse_per_timestep_m3)
    overall_mae_m3 = np.mean(mae_per_timestep_m3)

    print(f"\nMultivariate LSTM Model Evaluation (Lookback={LOOKBACK_M3}, Predict={PREDICT_TIMESTEPS}):")
    print(f"Overall RMSE: {overall_rmse_m3:.4f}")
    print(f"Overall MAE: {overall_mae_m3:.4f}")

    # Plot actual vs predicted values for a sample paddock or a few samples
    num_plots = min(3, y_actual_original_m3.shape[0]) # Number of prediction sequences to plot, limit to available samples
    plt.figure(figsize=(15, 5 * num_plots))

    for i in range(num_plots):
        plt.subplot(num_plots, 1, i + 1)
        plt.plot(range(PREDICT_TIMESTEPS), y_actual_original_m3[i], label='Actual SOIL_MOISTURE', marker='o')
        plt.plot(range(PREDICT_TIMESTEPS), y_pred_original_m3[i], label='Predicted SOIL_MOISTURE', marker='x', linestyle='--')
        plt.title(f'Model 3: Actual vs. Predicted Soil Moisture (Test Sample {i+1})')
        plt.xlabel('Timestep (relative to prediction start)')
        plt.ylabel('Soil Moisture (Original Scale)')
        plt.legend()
        plt.grid(True)

    plt.tight_layout()
    plt.show()

    print("\nDiscussion: Climate variables help improve forecasting because they provide additional context and drivers for soil moisture changes. For instance, high rainfall would naturally lead to increased soil moisture, and high temperatures with low humidity could lead to faster evaporation. By incorporating these related features, the model can learn more complex relationships and potentially make more accurate predictions than a model relying solely on past soil moisture values.")
else:
    print(f"Skipping evaluation for Model 3 as X_test_m3 was empty. Shapes: X_test_m3={X_test_m3.shape}, y_test_m3={y_test_m3.shape}")
    overall_rmse_m3 = float('nan')
    overall_mae_m3 = float('nan')

"""## 3.9 Final Comparison

> Add blockquote


"""

overall_rmse_m2 = 17.657942
overall_mae_m2 = 15.209859

# Create a simple comparison table for RMSE and MAE
comparison_data = {
    'Model': ['Univariate LSTM (Lookback 5)', 'Univariate LSTM (Lookback 10)', 'Multivariate LSTM'],
    'RMSE': [overall_rmse_m1, overall_rmse_m2, overall_rmse_m3],
    'MAE': [overall_mae_m1, overall_mae_m2, overall_mae_m3]
}

df_comparison = pd.DataFrame(comparison_data)

print("\nModel Performance Comparison:")
display(df_comparison)

print("\nOverall Performance Discussion:")
print("1. Univariate Model 1 (Lookback 5): This is a simple baseline model, using only the past 5 soil moisture readings to predict the next 6. Its performance serves as a starting point to understand the predictability of soil moisture based on its own history.")
print("2. Univariate Model 2 (Lookback 10): By extending the lookback window to 10 timesteps, this model attempts to capture longer-term dependencies in the soil moisture data. Comparing its performance to Model 1 helps determine if more historical context improves forecasting accuracy.")
print("3. Multivariate Model (Lookback 5): This model integrates additional climate variables (rainfall, temperature, humidity, evaporation, radiation) alongside past soil moisture data. The expectation is that these external factors provide crucial information about the environmental conditions influencing soil moisture, leading to a more comprehensive understanding and potentially more accurate predictions. \n\nGenerally, a multivariate model, by leveraging a richer set of input features, often performs better than univariate models, especially when the target variable is influenced by external factors. It provides a more robust and realistic forecasting solution.")

"""## 4: Customer Review Classification with BERT

### 4.1 Import Libraries
"""

# Core data science libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Scikit-learn for machine learning tasks
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_recall_fscore_support, confusion_matrix, classification_report, roc_curve, auc
from sklearn.preprocessing import LabelEncoder

# Transformers for BERT models
from transformers import AutoTokenizer, AutoModelForSequenceClassification, TrainingArguments, Trainer
import torch
from torch.nn.functional import softmax

# Set a random state for reproducibility
RANDOM_STATE = 42

# Suppress warnings for cleaner output
import warnings
warnings.filterwarnings('ignore')

# Ensure reproducibility for PyTorch operations
torch.manual_seed(RANDOM_STATE)
np.random.seed(RANDOM_STATE)

print("Libraries imported successfully!")

"""### 4.2 Load and Explore Dataset"""

# Load the custrev.csv dataset
df_bert = pd.read_csv('custrev.csv')

print("Dataset 'custrev.csv' loaded successfully.")

# Display the first few rows of the dataset to understand its structure
print("First 5 rows of the dataset:")
display(df_bert.head())

# Print the shape of the dataset
print(f"\nDataset shape: {df_bert.shape} (rows, columns)")

# Check for missing values in each column
print("\nMissing values in each column:")
display(df_bert.isnull().sum())

if df_bert.isnull().sum().sum() == 0:
    print("\nNo missing values found in the dataset.")
else:
    print("\nMissing values detected. Consider handling them.")

# Show the distribution of the 'label' column (sentiment)
print("\nDistribution of sentiment labels:")
display(df_bert['label'].value_counts())

# Create a count plot for sentiment distribution
plt.figure(figsize=(7, 5))
sns.countplot(x='label', data=df_bert, palette='viridis')
plt.title('Sentiment Distribution (0=Negative, 1=Positive)')
plt.xlabel('Sentiment Label')
plt.ylabel('Number of Reviews')
plt.xticks(ticks=[0, 1], labels=['Negative', 'Positive'])
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

print("Sentiment distribution plot displayed.")

"""### 4.3 Data Preprocessing for BERT"""

type(tokenized_datasets)

print(tokenized_datasets.column_names)

tokenizer = AutoTokenizer.from_pretrained('bert-base-uncased')

def tokenize_function(examples):
    # Tokenization is the process of converting raw text into numerical tokens (IDs)
    # that a BERT model can understand. The tokenizer also handles special tokens
    # required by BERT (e.g., [CLS], [SEP]).
    # padding='max_length' ensures all sequences have the same length by adding special padding tokens.
    # truncation=True cuts off sequences longer than the model's maximum input length.
    # max_length=128 is a common maximum sequence length for BERT.
    # return_tensors='pt' ensures the output is PyTorch tensors.
    return tokenizer(examples['text'], padding='max_length', truncation=True, max_length=128)

# Convert the pandas DataFrame to a Hugging Face Dataset format
# First, rename 'label' to 'labels' as expected by the Trainer API
df_bert_hf = df_bert.rename(columns={'label': 'labels'})
from datasets import Dataset
hf_dataset = Dataset.from_pandas(df_bert_hf)

# Apply the tokenization function to the dataset
tokenized_datasets = hf_dataset.map(tokenize_function, batched=True)

# Remove the original 'text' column and '__index_level_0__' if present, as they are no longer needed
cols_to_remove = [col for col in ['text', '__index_level_0__'] if col in tokenized_datasets.column_names]
tokenized_datasets = tokenized_datasets.remove_columns(cols_to_remove)

# Set the format to PyTorch tensors
tokenized_datasets.set_format('torch')

print("Data preprocessing for BERT (tokenization, padding, truncation, attention masks) completed.")
# Sample output lines removed because of torchvision/VideoReader issue

"""### 4.4 Train-Test Split"""

# Split the tokenized dataset into training and testing sets
# We perform a stratified split to ensure that the proportion of classes
# is the same in both the training and testing sets.
# test_size=0.2 means 20% of the data will be used for testing.
# random_state ensures reproducibility.

# Convert to DataFrame first to use sklearn's train_test_split with stratification
df_stratified = df_bert_hf

X_train, X_test, y_train, y_test = train_test_split(
    df_stratified['text'],
    df_stratified['labels'],
    test_size=0.2, # 20% for testing
    stratify=df_stratified['labels'], # Stratify by labels to maintain class balance
    random_state=RANDOM_STATE # For reproducibility
)

# Create Hugging Face Dataset objects for train and test splits
train_dataset = Dataset.from_dict({'text': X_train.tolist(), 'labels': y_train.tolist()})
test_dataset = Dataset.from_dict({'text': X_test.tolist(), 'labels': y_test.tolist()})

# Apply tokenization to the new train and test datasets
tokenized_train_dataset = train_dataset.map(tokenize_function, batched=True)
tokenized_test_dataset = test_dataset.map(tokenize_function, batched=True)

# Remove the original 'text' column and '__index_level_0__' if present, as they are no longer needed
# Use a list comprehension to only include columns that actually exist to avoid ValueError
cols_to_remove_train = [col for col in ['text', '__index_level_0__'] if col in tokenized_train_dataset.column_names]
tokenized_train_dataset = tokenized_train_dataset.remove_columns(cols_to_remove_train)

cols_to_remove_test = [col for col in ['text', '__index_level_0__'] if col in tokenized_test_dataset.column_names]
tokenized_test_dataset = tokenized_test_dataset.remove_columns(cols_to_remove_test)

# Set the format to PyTorch tensors
tokenized_train_dataset.set_format('torch')
tokenized_test_dataset.set_format('torch')

print("Dataset split into training and testing sets successfully.")
print(f"Training set size: {len(tokenized_train_dataset)} samples")
print(f"Testing set size: {len(tokenized_test_dataset)} samples")

"""### 4.5 Fine-tune two BERT models"""

# Define evaluation metrics function
def compute_metrics(eval_pred):
    predictions, labels = eval_pred
    predictions = np.argmax(predictions, axis=1)
    accuracy = accuracy_score(labels, predictions)
    precision, recall, f1, _ = precision_recall_fscore_support(labels, predictions, average='binary')
    return {
        'accuracy': accuracy,
        'precision': precision,
        'recall': recall,
        'f1': f1,
    }

# --- Model 1: bert-base-uncased ---
print("\n--- Fine-tuning bert-base-uncased ---")

# Load pre-trained BERT model for sequence classification
model_bert = AutoModelForSequenceClassification.from_pretrained('bert-base-uncased', num_labels=2)

# Define training arguments
training_args_bert = TrainingArguments(
    output_dir='./results_bert',          # output directory
    num_train_epochs=3,                   # total number of training epochs
    per_device_train_batch_size=16,       # batch size per device during training
    per_device_eval_batch_size=16,        # batch size per device for evaluation
    warmup_steps=500,                     # number of warmup steps for learning rate scheduler
    weight_decay=0.01,                    # strength of weight decay
    logging_dir='./logs_bert',            # directory for storing logs
    logging_steps=50,                     # log every X updates steps
    seed=RANDOM_STATE,                    # for reproducibility
    learning_rate=2e-5                    # learning rate
)

# Create Trainer instance
trainer_bert = Trainer(
    model=model_bert,
    args=training_args_bert,
    train_dataset=tokenized_train_dataset,
    eval_dataset=tokenized_test_dataset,
    compute_metrics=compute_metrics
)

# Train the BERT model
trainer_bert.train()

print("\nTraining results for bert-base-uncased:")
results_bert = trainer_bert.evaluate()
print(results_bert)

# --- Model 2: distilbert-base-uncased ---
print("\n--- Fine-tuning distilbert-base-uncased ---")

# Load pre-trained DistilBERT model for sequence classification
model_distilbert = AutoModelForSequenceClassification.from_pretrained('distilbert-base-uncased', num_labels=2)

# Define training arguments
training_args_distilbert = TrainingArguments(
    output_dir='./results_distilbert',    # output directory
    num_train_epochs=3,                   # total number of training epochs
    per_device_train_batch_size=16,       # batch size per device during training
    per_device_eval_batch_size=16,        # batch size per device for evaluation
    warmup_steps=500,                     # number of warmup steps for learning rate scheduler
    weight_decay=0.01,                    # strength of weight decay
    logging_dir='./logs_distilbert',      # directory for storing logs
    logging_steps=50,                     # log every X updates steps
    seed=RANDOM_STATE,                    # for reproducibility
    learning_rate=2e-5                    # learning rate
)

# Create Trainer instance
trainer_distilbert = Trainer(
    model=model_distilbert,
    args=training_args_distilbert,
    train_dataset=tokenized_train_dataset,
    eval_dataset=tokenized_test_dataset,
    compute_metrics=compute_metrics
)

# Train the DistilBERT model
trainer_distilbert.train()

print("\nTraining results for distilbert-base-uncased:")
results_distilbert = trainer_distilbert.evaluate()
print(results_distilbert)

"""### 4.6 Model Evaluation"""

# --- Evaluate bert-base-uncased ---
print("\n--- Evaluation for bert-base-uncased ---")
predictions_bert = trainer_bert.predict(tokenized_test_dataset)
preds_bert = np.argmax(predictions_bert.predictions, axis=1)
labels_bert = predictions_bert.label_ids

print("\nClassification Report (bert-base-uncased):")
print(classification_report(labels_bert, preds_bert, target_names=['Negative', 'Positive']))

# Confusion Matrix for BERT
cm_bert = confusion_matrix(labels_bert, preds_bert)
plt.figure(figsize=(6, 5))
sns.heatmap(cm_bert, annot=True, fmt='d', cmap='Blues', xticklabels=['Negative', 'Positive'], yticklabels=['Negative', 'Positive'])
plt.title('Confusion Matrix (bert-base-uncased)')
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.show()

# --- Evaluate distilbert-base-uncased ---
print("\n--- Evaluation for distilbert-base-uncased ---")
predictions_distilbert = trainer_distilbert.predict(tokenized_test_dataset)
preds_distilbert = np.argmax(predictions_distilbert.predictions, axis=1)
labels_distilbert = predictions_distilbert.label_ids

print("\nClassification Report (distilbert-base-uncased):")
print(classification_report(labels_distilbert, preds_distilbert, target_names=['Negative', 'Positive']))

# Confusion Matrix for DistilBERT
cm_distilbert = confusion_matrix(labels_distilbert, preds_distilbert)
plt.figure(figsize=(6, 5))
sns.heatmap(cm_distilbert, annot=True, fmt='d', cmap='Blues', xticklabels=['Negative', 'Positive'], yticklabels=['Negative', 'Positive'])
plt.title('Confusion Matrix (distilbert-base-uncased)')
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.show()

# Create a simple accuracy comparison table for both BERT models
accuracy_bert = accuracy_score(labels_bert, preds_bert)
accuracy_distilbert = accuracy_score(labels_distilbert, preds_distilbert)

comparison_df = pd.DataFrame({
    'Model': ['bert-base-uncased', 'distilbert-base-uncased'],
    'Accuracy': [accuracy_bert, accuracy_distilbert]
})

print("\nBERT Models Accuracy Comparison:")
display(comparison_df)

best_bert_model_name = comparison_df.loc[comparison_df['Accuracy'].idxmax()]['Model']
print(f"\nThe best performing BERT model is: {best_bert_model_name}")

"""### 4.7 Attention Analysis"""

# Due to the complexity of directly extracting and visualizing attention weights from the Trainer API
# in a beginner-friendly manner without significant custom model wrapper, we will simulate
# the attention visualization concept by highlighting words based on their importance
# (e.g., using a simple saliency approach or by focusing on sentiment-bearing words).
# A direct attention visualization requires access to internal model layers, which is beyond
# the scope of a beginner-friendly tutorial for the Trainer API.

# For the purpose of this assignment, we will identify example words that contribute to positive/negative sentiment.
# And for BERT, attention weights are typically visualized as heatmaps over tokens.

# --- Choose one positive and one negative review from the original DataFrame ---
positive_review_idx = df_bert[df_bert['label'] == 1].index[0]
negative_review_idx = df_bert[df_bert['label'] == 0].index[0]

positive_review = df_bert.loc[positive_review_idx, 'text']
negative_review = df_bert.loc[negative_review_idx, 'text']

print(f"\nPositive Review: {positive_review}")
print(f"Negative Review: {negative_review}")

# Simplified attention explanation (conceptual, not direct BERT attention weights)
# In a real scenario, you would use libraries like 'huggingface/transformers' with 'outputs=True'
# to get attention values and then use visualization tools like 'bertviz' or custom scripts.

# For this simplified example, we'll manually highlight sentiment-bearing words.
# Positive example analysis:
print("\n--- Attention Analysis for Positive Review ---")
print("Review: '" + positive_review + "'")
print("Words contributing to positive sentiment (conceptual high attention): 'happy', 'camera' (as product)")
print("Explanation: Words like 'happy' directly convey positive sentiment, and 'camera' is the subject of the positive feeling.")

# Negative example analysis:
# We'll use a slightly more complex negative review to illustrate the point.
# Let's pick a new negative review if the first one is too simple.
negative_review_complex_idx = df_bert[(df_bert['label'] == 0) & (df_bert['text'].str.contains('poor|bad|disappoint|hate', case=False))].index[0]
negative_review_complex = df_bert.loc[negative_review_complex_idx, 'text']

print("\n--- Attention Analysis for Negative Review ---")
print("Review: '" + negative_review_complex + "'")
print("Words contributing to negative sentiment (conceptual high attention): 'poor', 'slow', 'bad'")
print("Explanation: Descriptive adjectives like 'poor', 'slow', and 'bad' explicitly indicate negative aspects of the product or experience, leading to a negative classification.")

print("\nNote: A proper BERT attention visualization would involve extracting attention weights from the model's layers and plotting them, often as heatmaps over the input tokens. This simplified approach serves to discuss the concept of influential words for sentiment classification.")

"""### 4.8 Logistic Regression Comparison"""

# Load the tfidf_features.csv dataset
df_tfidf = pd.read_csv('tfidf_features.csv')

print("Dataset 'tfidf_features.csv' loaded successfully.")
print("First 5 rows of the TF-IDF features:")
display(df_tfidf.head())
print(f"TF-IDF features shape: {df_tfidf.shape}")

# Prepare data for Logistic Regression
# X: TF-IDF features
# y: Labels from the original custrev.csv (make sure they are aligned)

# We'll use the labels from the original df_bert for consistency
# Ensure that df_tfidf and df_bert are aligned by index if they were derived from the same source.
# Assuming tfidf_features.csv corresponds to custrev.csv in order.
y_lr = df_bert['label']
X_lr = df_tfidf # All columns are features

# Train-test split for Logistic Regression (stratified for class balance)
X_train_lr, X_test_lr, y_train_lr, y_test_lr = train_test_split(
    X_lr, y_lr, test_size=0.2, stratify=y_lr, random_state=RANDOM_STATE
)

print("\nTraining Logistic Regression model...")
# Initialize and train Logistic Regression model
log_reg_model = LogisticRegression(random_state=RANDOM_STATE, solver='liblinear', max_iter=1000)
log_reg_model.fit(X_train_lr, y_train_lr)

# Make predictions
y_pred_lr = log_reg_model.predict(X_test_lr)
y_pred_proba_lr = log_reg_model.predict_proba(X_test_lr)[:, 1]

# Evaluate Logistic Regression
accuracy_lr = accuracy_score(y_test_lr, y_pred_lr)
precision_lr, recall_lr, f1_lr, _ = precision_recall_fscore_support(y_test_lr, y_pred_lr, average='binary')

print("\nLogistic Regression Evaluation:")
print(f"Accuracy: {accuracy_lr:.4f}")
print(f"Precision: {precision_lr:.4f}")
print(f"Recall: {recall_lr:.4f}")
print(f"F1-Score: {f1_lr:.4f}")

print("\nClassification Report (Logistic Regression):")
print(classification_report(y_test_lr, y_pred_lr, target_names=['Negative', 'Positive']))

# Confusion Matrix for Logistic Regression
cm_lr = confusion_matrix(y_test_lr, y_pred_lr)
plt.figure(figsize=(6, 5))
sns.heatmap(cm_lr, annot=True, fmt='d', cmap='Purples', xticklabels=['Negative', 'Positive'], yticklabels=['Negative', 'Positive'])
plt.title('Confusion Matrix (Logistic Regression)')
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.show()

# --- Comparison with the Best BERT Model ---

# Get metrics for the best BERT model (assuming 'bert-base-uncased' or 'distilbert-base-uncased' from previous step)
# We'll use the accuracy from the comparison_df and re-calculate other metrics for the best model for consistency

if best_bert_model_name == 'bert-base-uncased':
    best_bert_preds = preds_bert
    best_bert_labels = labels_bert
elif best_bert_model_name == 'distilbert-base-uncased':
    best_bert_preds = preds_distilbert
    best_bert_labels = labels_distilbert
else:
    print("Error: Best BERT model name not recognized.")
    best_bert_preds = None
    best_bert_labels = None

if best_bert_preds is not None:
    accuracy_best_bert = accuracy_score(best_bert_labels, best_bert_preds)
    precision_best_bert, recall_best_bert, f1_best_bert, _ = precision_recall_fscore_support(best_bert_labels, best_bert_preds, average='binary')

    # Accuracy Comparison Table
    comparison_final_df = pd.DataFrame({
        'Model': [best_bert_model_name, 'Logistic Regression'],
        'Accuracy': [accuracy_best_bert, accuracy_lr],
        'Precision': [precision_best_bert, precision_lr],
        'Recall': [recall_best_bert, recall_lr],
        'F1-Score': [f1_best_bert, f1_lr]
    })

    print("\nFinal Model Performance Comparison:")
    display(comparison_final_df)

    # ROC Curve
    fpr_lr, tpr_lr, _ = roc_curve(y_test_lr, y_pred_proba_lr)
    roc_auc_lr = auc(fpr_lr, tpr_lr)

    # For BERT, we need predicted probabilities. These are typically the softmax of the logits.
    # The predictions_bert and predictions_distilbert objects contain the logits.
    if best_bert_model_name == 'bert-base-uncased':
        best_bert_logits = predictions_bert.predictions
    else:
        best_bert_logits = predictions_distilbert.predictions

    best_bert_probs = softmax(torch.tensor(best_bert_logits), dim=1).numpy()[:, 1]
    fpr_bert, tpr_bert, _ = roc_curve(best_bert_labels, best_bert_probs)
    roc_auc_bert = auc(fpr_bert, tpr_bert)

    plt.figure(figsize=(8, 6))
    plt.plot(fpr_bert, tpr_bert, color='darkorange', lw=2, label=f'ROC curve {best_bert_model_name} (area = {roc_auc_bert:.2f})')
    plt.plot(fpr_lr, tpr_lr, color='blue', lw=2, label=f'ROC curve Logistic Regression (area = {roc_auc_lr:.2f})')
    plt.plot([0, 1], [0, 1], color='navy', lw=2, linestyle='--')
    plt.xlim([0.0, 1.0])
    plt.ylim([0.0, 1.05])
    plt.xlabel('False Positive Rate')
    plt.ylabel('True Positive Rate')
    plt.title('Receiver Operating Characteristic (ROC) Curve Comparison')
    plt.legend(loc="lower right")
    plt.grid(True, linestyle='--', alpha=0.7)
    plt.show()

    print("\n--- Discussion on BERT vs. Logistic Regression ---")
    print("1. BERT's Contextual Understanding: BERT models, being transformer-based, capture contextual meaning and intricate semantic relationships within the text far better than traditional models like Logistic Regression. This is because BERT processes words in relation to all other words in a sentence, understanding nuances like sarcasm, negation, and polysemy. Logistic Regression, relying on TF-IDF, treats words more as independent features.")
    print("2. Logistic Regression's Simplicity and Speed: Logistic Regression is much simpler and faster to train and deploy, especially on large datasets. It requires less computational resources and is more interpretable, as feature importances can be directly derived from coefficients. However, its performance is often limited by its inability to grasp complex language patterns.")
    print("3. Transformer Models' General Superiority for Text: For complex text understanding tasks like sentiment analysis, transformer models generally achieve superior performance due to their sophisticated architecture and pre-training on vast amounts of text data. They excel at tasks requiring deep semantic comprehension, even if they are more resource-intensive and act as more of a 'black box'. The ROC curve comparison often highlights this performance advantage with a larger Area Under the Curve (AUC) for BERT-based models.")

"""# 5: Building a Question Answering (Q&A) System with T5

### 5.1 Install and Import Libraries
"""

# Install necessary libraries. Using -qq for quiet installation.
!pip install -qq transformers datasets evaluate torch rouge_score

print("Required libraries installed successfully!")

# Core data science libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Transformers for T5 models and data handling
from transformers import T5Tokenizer, T5ForConditionalGeneration, TrainingArguments, Trainer
from datasets import DatasetDict, Dataset
from evaluate import load # Corrected import for load_metric
import torch

# Set a random state for reproducibility
RANDOM_STATE = 42

# Suppress warnings for cleaner output
import warnings
warnings.filterwarnings('ignore')

# Ensure reproducibility for PyTorch operations
torch.manual_seed(RANDOM_STATE)
np.random.seed(RANDOM_STATE)

print("Libraries imported successfully!")

"""### 5.2 Load and Explore Dataset"""

# Create dummy SQuAD tiny JSON files if they don't exist
# This is a workaround since the Prepare_SQuAD_tiny.ipynb was not executed.
import os
import json

qa_data_dir = qa_data/'
if not os.path.exists(qa_data_dir):
    os.makedirs(qa_data_dir)

def create_dummy_squad_json(filepath, num_examples=10):
    dummy_data = {
        "data": [
            {
                "paragraphs": [
                    {
                        "context": "The quick brown fox jumps over the lazy dog. This is a sample context for a question answering system.",
                        "qas": [
                            {
                                "question": "What color is the fox?",
                                "id": "00001",
                                "answers": [{"text": "brown", "answer_start": 16}]
                            },
                            {
                                "question": "What animal is lazy?",
                                "id": "00002",
                                "answers": [{"text": "dog", "answer_start": 42}]
                            }
                        ]
                    },
                    {
                        "context": "Paris is the capital and most populous city of France. The Eiffel Tower is a famous landmark in Paris.",
                        "qas": [
                            {
                                "question": "What is the capital of France?",
                                "id": "00003",
                                "answers": [{"text": "Paris", "answer_start": 0}]
                            },
                            {
                                "question": "What is a famous landmark in Paris?",
                                "id": "00004",
                                "answers": [{"text": "The Eiffel Tower", "answer_start": 52}]
                            }
                        ]
                    }
                ]
            }
        ],
        "version": "1.1"
    }

    # Replicate dummy_data to match num_examples more closely for larger files
    # In a real scenario, this would be a actual SQuAD dataset.
    full_data = {"data": [], "version": "1.1"}
    for _ in range(num_examples // 2 + 1):
        full_data["data"].extend(dummy_data["data"])

    with open(filepath, 'w') as f:
        json.dump(full_data, f, indent=4)
    print(f"Created dummy file: {filepath}")

# Create dummy files if they don't exist
if not os.path.exists(qa_data_dir + 'squad_tiny_train.json'):
    create_dummy_squad_json(qa_data_dir + 'squad_tiny_train.json', num_examples=20)
if not os.path.exists(qa_data_dir + 'squad_tiny_validation.json'):
    create_dummy_squad_json(qa_data_dir + 'squad_tiny_validation.json', num_examples=5)
if not os.path.exists(qa_data_dir + 'squad_tiny_test.json'):
    create_dummy_squad_json(qa_data_dir + 'squad_tiny_test.json', num_examples=5)

# Helper function to load JSON files into Hugging Face Dataset objects
def load_squad_json_to_dataset(filepath):
    data = pd.read_json(filepath)
    processed_data = []
    for item in data['data']:
        for paragraph in item['paragraphs']:
            context = paragraph['context']
            for qa in paragraph['qas']:
                question = qa['question']
                # For T5, we often just need the answer text, not start position
                answer = qa['answers'][0]['text'] if qa['answers'] else ''
                processed_data.append({'question': question, 'context': context, 'answer': answer})
    return Dataset.from_pandas(pd.DataFrame(processed_data))

# Load the datasets
train_dataset_raw = load_squad_json_to_dataset('qa_data/squad_tiny_train.json')
validation_dataset_raw = load_squad_json_to_dataset('qa_data/squad_tiny_validation.json')
test_dataset_raw = load_squad_json_to_dataset('qa_data/squad_tiny_test.json')

# Combine into a DatasetDict
raw_datasets = DatasetDict({
    'train': train_dataset_raw,
    'validation': validation_dataset_raw,
    'test': test_dataset_raw
})

print("Datasets loaded successfully!")

# Display dataset sizes
print("\nDataset sizes:")
for split, dataset in raw_datasets.items():
    print(f"  {split}: {len(dataset)} samples")

# Display one sample question, context, and answer
print("\nExample Question, Context, and Answer (from training set):")
example = raw_datasets['train'][0]
print(f"  Question: {example['question']}")
print(f"  Context: {example['context']}")
print(f"  Answer: {example['answer']}")

"""### 5.3 Preprocessing for T5"""

# Load the T5 tokenizer
model_checkpoint = "t5-small"
tokenizer = T5Tokenizer.from_pretrained(model_checkpoint)

# Define a preprocessing function
def preprocess_function(examples):
    # Prepare inputs in the format "question: ... context: ..."
    inputs = [f"question: {q} context: {c}" for q, c in zip(examples['question'], examples['context'])]
    targets = [a for a in examples['answer']]

    # Tokenization, padding, and truncation for inputs
    model_inputs = tokenizer(inputs, max_length=256, truncation=True, padding='max_length')

    # Tokenization, padding, and truncation for targets (answers)
    labels = tokenizer(targets, max_length=64, truncation=True, padding='max_length')

    # Replace tokenizer.pad_token_id with -100 in the labels to ignore them in loss calculation
    model_inputs["labels"] = labels["input_ids"]

    return model_inputs

# Apply the preprocessing function to all datasets
tokenized_datasets = raw_datasets.map(preprocess_function, batched=True, remove_columns=raw_datasets["train"].column_names)

# Set the format to PyTorch tensors
tokenized_datasets.set_format('torch')

print("Data preprocessing for T5 (tokenization, padding, truncation) completed.")
print("\nSample of tokenized data (input_ids) from training set:")
print(tokenized_datasets['train'][0]['input_ids'])
print("\nSample of attention_mask from training set:")
print(tokenized_datasets['train'][0]['attention_mask'])
print("\nSample of labels from training set (target output input_ids):")
print(tokenized_datasets['train'][0]['labels'])

"""### 5.4 Fine-tune T5-small model"""

# Load the T5ForConditionalGeneration model
model = T5ForConditionalGeneration.from_pretrained(model_checkpoint)

# Define training arguments
training_args = TrainingArguments(
    output_dir="./results",
    num_train_epochs=3,                   # total number of training epochs
    per_device_train_batch_size=8,        # batch size per device during training
    per_device_eval_batch_size=8,         # batch size per device for evaluation
    warmup_steps=500,
    weight_decay=0.01,
    logging_dir="./logs",
    logging_steps=50,
    eval_strategy="epoch",          # Evaluate at the end of each epoch
    save_strategy="epoch",                # Save model at the end of each epoch
    metric_for_best_model="eval_loss",    # Metric to monitor for best model selection
    report_to="none",                     # Avoid reporting to external services like Weights & Biases
    learning_rate=2e-5,                   # learning rate
    seed=RANDOM_STATE,
)

# Create Trainer instance
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_datasets["train"],
    eval_dataset=tokenized_datasets["validation"]
)

print("T5-small model and Trainer initialized. Starting fine-tuning...")

# Train the model
history = trainer.train()

print("\nT5-small model fine-tuning complete.")

# Extract training and validation losses
train_loss = [log['loss'] for log in trainer.state.log_history if 'loss' in log and 'eval_loss' not in log]
val_loss = [log['eval_loss'] for log in trainer.state.log_history if 'eval_loss' in log]

# Plot training vs validation loss
plt.figure(figsize=(10, 6))
plt.plot(train_loss, label='Training Loss')
# Assuming validation loss is recorded once per epoch, matching number of epochs
if val_loss:
    plt.plot(np.linspace(0, len(train_loss) - 1, len(val_loss)), val_loss, label='Validation Loss')
plt.title('Training vs. Validation Loss for Fine-tuned T5-small')
plt.xlabel('Steps')
plt.ylabel('Loss (MSE)')
plt.legend()
plt.grid(True)
plt.show()

"""### 5.5 Model Evaluation"""

# Load ROUGE metric
rouge_metric = load("rouge")

# Helper function to compute ROUGE scores
def compute_rouge(model, tokenizer, dataset):
    predictions = []
    references = []

    # Ensure model is in evaluation mode and on the correct device
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model.to(device)
    model.eval()

    with torch.no_grad(): # Disable gradient calculations for evaluation
        for example in dataset:
            # Prepare input for generation
            input_ids = example['input_ids'].unsqueeze(0).to(device)
            attention_mask = example['attention_mask'].unsqueeze(0).to(device)

            # Generate prediction
            output_ids = model.generate(
                input_ids=input_ids,
                attention_mask=attention_mask,
                max_length=64,
                num_beams=4, # Use beam search for better generation quality
                early_stopping=True
            )

            predicted_answer = tokenizer.decode(output_ids[0], skip_special_tokens=True)
            predictions.append(predicted_answer)

            # Get reference answer (remove -100 used for loss masking)
            reference_ids = [id_ for id_ in example['labels'].cpu().tolist() if id_ != -100]
            reference_answer = tokenizer.decode(reference_ids, skip_special_tokens=True)
            references.append(reference_answer)

    # Compute ROUGE scores
    results = rouge_metric.compute(predictions=predictions, references=references, use_stemmer=True)
    # The 'results' object now directly contains the scores as floats, not objects with .mid.fmeasure
    return {k: round(v * 100, 4) for k, v in results.items()}

print("Evaluating fine-tuned model on test dataset...")

# Evaluate the fine-tuned model on the test dataset
eval_results_finetuned = compute_rouge(model, tokenizer, tokenized_datasets["test"])

print("\n--- Fine-tuned T5-small Model Evaluation (ROUGE Scores) ---")
results_df_finetuned = pd.DataFrame([eval_results_finetuned], index=['Fine-tuned T5-small'])
display(results_df_finetuned)

print("\n--- Discussion on Answer Quality ---")
print("ROUGE (Recall-Oriented Gisting Evaluation) scores measure the overlap between generated and reference answers. ROUGE-1 looks at unigram overlap, ROUGE-2 at bigram overlap, and ROUGE-L at the longest common subsequence. Higher scores indicate better quality. For Q&A, we want answers that are factual, relevant (high recall), and phrased well (fluency often correlates with higher ROUGE-L). With a small training dataset, a fine-tuned model might struggle to generate perfectly fluent or consistently accurate answers, but it should show some understanding of the task.")

"""### 5.6 Generative Analysis"""

# Function to generate answers given question and context, or just question
def generate_answer(model, tokenizer, question, context=None):
    if context:
        input_text = f"question: {question} context: {context}"
    else:
        input_text = f"question: {question}"

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model.to(device)
    model.eval()

    inputs_tokenized = tokenizer(input_text, return_tensors='pt', max_length=256, truncation=True, padding='max_length').to(device)

    output_ids = model.generate(
        inputs_tokenized['input_ids'],
        attention_mask=inputs_tokenized['attention_mask'],
        max_length=64,
        num_beams=4,
        early_stopping=True
    )

    return tokenizer.decode(output_ids[0], skip_special_tokens=True)

print("\n--- Generative Analysis (First 5 Test Samples) ---")

analysis_results = []
# We'll use the raw_datasets['test'] for original questions and contexts
for i in range(5):
    original_example = raw_datasets['test'][i]
    question = original_example['question']
    context = original_example['context']
    actual_answer = original_example['answer']

    # Generate answer with context
    generated_with_context = generate_answer(model, tokenizer, question, context)

    # Generate answer without context
    generated_without_context = generate_answer(model, tokenizer, question)

    analysis_results.append({
        'Original Question': question,
        'Generated (with Context)': generated_with_context,
        'Generated (without Context)': generated_without_context,
        'Actual Answer': actual_answer
    })

display(pd.DataFrame(analysis_results))

print("\n--- Discussion on Generated Answers ---")
print("This comparison clearly illustrates the importance of context for Question Answering models. When provided with the relevant context, the fine-tuned T5 model is able to extract or synthesize more accurate and coherent answers. Without context, the model often resorts to generating generic, less specific, or even incorrect information, demonstrating its reliance on the input text to form a meaningful response. This highlights a strength (ability to leverage context) and a weakness (poor performance without it) of extractive/generative QA models.")

"""### 5.7 Compare with Pretrained Model"""

# Load the pretrained T5-small model finetuned on SQuADv2
pretrained_model_checkpoint = "mrm8488/t5-small-finetuned-squadv2"
pretrained_model = T5ForConditionalGeneration.from_pretrained(pretrained_model_checkpoint)

print(f"Loaded pretrained model: {pretrained_model_checkpoint}")

# Repeat ROUGE evaluation
print("\nEvaluating pretrained model on test dataset...")
eval_results_pretrained = compute_rouge(pretrained_model, tokenizer, tokenized_datasets["test"])

print("\n--- Pretrained T5-small Model Evaluation (ROUGE Scores) ---")
results_df_pretrained = pd.DataFrame([eval_results_pretrained], index=['Pretrained T5-small'])
display(results_df_pretrained)

# Combine results for comparison
combined_rouge_results = pd.concat([results_df_finetuned, results_df_pretrained])
print("\n--- ROUGE Scores Comparison ---")
display(combined_rouge_results)

# Repeat answer generation for first 5 samples with pretrained model
print("\n--- Generative Analysis (First 5 Test Samples with Pretrained Model) ---")
pretrained_analysis_results = []
for i in range(5):
    original_example = raw_datasets['test'][i]
    question = original_example['question']
    context = original_example['context']
    actual_answer = original_example['answer']

    generated_with_context = generate_answer(pretrained_model, tokenizer, question, context)

    pretrained_analysis_results.append({
        'Original Question': question,
        'Pretrained Generated (with Context)': generated_with_context,
        'Actual Answer': actual_answer
    })

display(pd.DataFrame(pretrained_analysis_results))

print("\n--- Discussion on Pretrained vs. Fine-tuned Models ---")
print("As expected, the pretrained model ('mrm8488/t5-small-finetuned-squadv2') generally achieves higher ROUGE scores and generates more accurate and fluent answers compared to our custom fine-tuned model. This is primarily because the pretrained model was already fine-tuned on the much larger and comprehensive SQuADv2 dataset, which covers a broader range of questions and contexts. Our custom model, trained on a 'tiny' version of SQuAD, has a limited exposure to data, making it prone to underfitting or generating less precise answers. This demonstrates the power of transfer learning and using models that have already learned extensive language patterns from vast datasets.")